Update all the required/necessary extensions for Rails SR page - http…
ExpediaInc/expedia-omg-tags pull request #103
Opened 2017-04-05 12:48 UTC by j-ibrahim

…s://trello.com/c/DVG9rgsw/205-update-all-the-required-necessary-extensions-for-rails-sr-page

2017-04-11 06:23 UTC, trungnguyenexp requested changes

2017-04-11 06:23 UTC, trungnguyenexp commented on src/library/simplified/extension/city-name.js
> +    b["city"] = b["qp.destinationName"].split(",")[0];
Try not to use qp.xxxx, we should use what we exposed, and qp is not one of them. If it gets removed in the future, this will break.
Better to use "entity.railSearch.searchParameters.arrivalStation.name" for destination.

2017-04-11 06:23 UTC, trungnguyenexp commented on src/library/simplified/extension/checkin-date.js
> +else if (utag.isRailSearchResults() && b['entity.railSearch.searchParameters.journeyLegs.0']!= undefined )
I would check for b['entity.railSearch.searchParameters.journeyLegs.0.isoFormatDate'] and if it exists, use it again inside the condition to retrieve the value. IF you only check for b['entity.railSearch.searchParameters.journeyLegs.0'], what happen if isoFormatDate doesn't exist?  I usually check for exactly what i'm looking for before i assign it.

2017-04-11 06:23 UTC, trungnguyenexp commented on src/library/simplified/extension/checkout-date.js
> +    b["checkOutDate"] = b['entity.railSearch.searchParameters.journeyLegs.1'].isoFormatDate;
Same comment as checkInDate above. I also noticed that .isoFormatDate doesn't exist in the UDO.

2017-04-11 06:23 UTC, trungnguyenexp commented on src/library/simplified/extension/number-of-guests.js
> +        for (var guest = 0 ; guest < b.entity.railSearch.searchResults.railLegs.get(0).railOfferItems.get(0).travelers.length; guest++)
Moving forward, we should avoid calculating the number of guests for all LOBs. I believe the UDO has and object where we can expose the total number of guests/travelers that we can use for each LOB. Currently, there is a bug where we are not calculating it correctly. Specifically for flights when using child in-lap.

2017-04-11 06:35 UTC, j-ibrahim commented on src/library/simplified/extension/city-name.js
> +    b["city"] = b["qp.destinationName"].split(",")[0];
Currently, we dont have "entity.railSearch.searchParameters.arrivalStation.name" correctly populated. It has only station name. From this parameter, we cannot retrieve city, state, country name.
![image](https://cloud.githubusercontent.com/assets/21168911/24895634/112e23aa-1eaf-11e7-8400-ace39d7a34c4.png)

2017-04-11 06:36 UTC, j-ibrahim commented on src/library/simplified/extension/checkin-date.js
> +else if (utag.isRailSearchResults() && b['entity.railSearch.searchParameters.journeyLegs.0']!= undefined )
I can add extra check for isoFormatDate also before assigning the value.

2017-04-11 06:37 UTC, j-ibrahim commented on src/library/simplified/extension/checkout-date.js
> +    b["checkOutDate"] = b['entity.railSearch.searchParameters.journeyLegs.1'].isoFormatDate;
isoFormatDate  existis in UDO. Please have a look at the screenshot.

![image](https://cloud.githubusercontent.com/assets/21168911/24895686/5634786e-1eaf-11e7-923d-b1599a74d130.png)

2017-04-11 06:42 UTC, trungnguyenexp requested changes

2017-04-11 06:42 UTC, trungnguyenexp commented on src/library/simplified/extension/state-name.js
> +    utag_data["state"] = b["qp.destinationName"].split(",")[1];
Avoid using qp

2017-04-11 06:45 UTC, trungnguyenexp commented on src/library/simplified/extension/state-name.js
> +    utag_data["state"] = b["qp.destinationName"].split(",")[1];
Also, there are old code at the bottom, please help us delete them :).

2017-04-11 06:46 UTC, trungnguyenexp commented on src/library/simplified/extension/city-name.js
> +    b["city"] = b["qp.destinationName"].split(",")[0];
I see what you are saying now. If that is the case, we need to find a way to expose it from the datapopulator. From what I understand, we should avoid using qp.

2017-04-11 06:47 UTC, trungnguyenexp commented on src/library/simplified/extension/checkin-date.js
> +else if (utag.isRailSearchResults() && b['entity.railSearch.searchParameters.journeyLegs.0']!= undefined )
not necessary to add a second check, just check it on line 8 is good enough, then assign it to checkInDate inside the block.

2017-04-11 06:48 UTC, trungnguyenexp commented on src/library/simplified/extension/checkout-date.js
> +    b["checkOutDate"] = b['entity.railSearch.searchParameters.journeyLegs.1'].isoFormatDate;
Don't use the object, please always use the flattened field, if the flatten field don't exists, it is a bug with our flattener.

2017-04-11 06:53 UTC, trungnguyenexp commented on src/library/simplified/extension/checkout-date.js
> +    b["checkOutDate"] = b['entity.railSearch.searchParameters.journeyLegs.1'].isoFormatDate;
The screenshot you have above is not flattented objects.

2017-04-11 07:10 UTC, trungnguyenexp commented on src/library/simplified/extension/checkin-date.js
> +else if (utag.isRailSearchResults() && b['entity.railSearch.searchParameters.journeyLegs.0']!= undefined )
please see comments under Conversion tab.

2017-04-11 07:10 UTC, trungnguyenexp commented on src/library/simplified/extension/checkout-date.js
> +    b["checkOutDate"] = b['entity.railSearch.searchParameters.journeyLegs.1'].isoFormatDate;
please see comments under Conversion tab.

2017-04-11 07:10 UTC, trungnguyenexp commented on src/library/simplified/extension/city-name.js
> +    b["city"] = b["qp.destinationName"].split(",")[0];
please see comments under Conversion tab.

2017-04-11 08:09 UTC, j-ibrahim commented on src/library/simplified/extension/city-name.js
> +    b["city"] = b["qp.destinationName"].split(",")[0];
okay Trung. Will check the possibility of bringing it to DataPopulator

2017-04-11 08:33 UTC, j-ibrahim commented on src/library/simplified/extension/checkout-date.js
> +    b["checkOutDate"] = b['entity.railSearch.searchParameters.journeyLegs.1'].isoFormatDate;
I think I need to correct somemore DataPopulator work in rails-web. I didnt consider ARRIVE By option when correcting DataPopulator. I tried like this and got everything correctly populator. I need to consider the scenario that you have mentioned.

![image](https://cloud.githubusercontent.com/assets/21168911/24899883/90245a52-1ebf-11e7-99d0-f77073845426.png)

2017-04-11 12:00 UTC, j-ibrahim commented on src/library/simplified/extension/state-name.js
> +    utag_data["state"] = b["qp.destinationName"].split(",")[1];
sure trung

2017-05-02 11:10 UTC, j-ibrahim commented
![country](https://cloud.githubusercontent.com/assets/21168911/25615536/6b924c52-2f55-11e7-81c1-fdaf1f2a41df.png)
![state](https://cloud.githubusercontent.com/assets/21168911/25615537/6b946fbe-2f55-11e7-9076-e8454c13d436.png)
![noofguests](https://cloud.githubusercontent.com/assets/21168911/25615534/6b90ae38-2f55-11e7-8b93-377f92afa001.png)
![city](https://cloud.githubusercontent.com/assets/21168911/25615535/6b90fdc0-2f55-11e7-97be-83087d3a116a.png)

Trung,

Changes are incorporated. 
1) Regarding the use of "qp", I had to modify the rails-web real code to bring it to the DataPopulator. But in real code also, they are taking the values from the URLs query parameter.  
2) CheckIn and Checkout Dates are updates with isoFormatDate check also
3) numberofguests is also updated as per your suggestion. 

Please have a look the changes and merge it if it is fine for you.

2017-05-02 12:17 UTC, merged