Updating u-parameters(u3,u14,u13) for doubleclick migration for packa…
ExpediaInc/expedia-omg-tags pull request #112
Opened 2017-04-25 14:03 UTC by yonaik

…ge search page

2017-04-25 15:50 UTC, trungnguyenexp requested changes

2017-04-25 15:50 UTC, trungnguyenexp commented on src/library/simplified/extension/origin-id.js
> +	b[''originId] = b['entity.packageSearch.packageSearchParameters.originRegionId'];
originId should be in between '',  b['originId']

2017-04-25 15:58 UTC, trungnguyenexp commented
If possible, could you run a test for each changes in the console and attach a screenshot of each result to this review moving forward? it would be faster for us to review :).

2017-04-26 04:07 UTC, yonaik commented
![packagesearch_u3 u13 and u14 params results in console](https://cloud.githubusercontent.com/assets/21304101/25417713/9b2d9b70-2a63-11e7-9e61-04def95a0cd0.png)

2017-04-26 04:49 UTC, trungnguyenexp approved these changes

2017-04-26 04:49 UTC, merged