Create marketingABTests in the UDO for exposing all the marketingABTe…
ExpediaInc/expedia-omg-tags pull request #162
Opened 2017-07-03 10:26 UTC by yonaik

…sts expId and it's bucket value

2017-07-03 10:28 UTC, yonaik commented
![marketingABTestsInHomepage.png…]()

2017-07-03 10:30 UTC, yonaik commented
Initially I have considered few sample marketingABTests values to check our solution works. 
We need to get active and running marketingABTests value from Guillermo in this case.

2017-07-03 19:54 UTC, trungguyen requested changes

2017-07-03 19:54 UTC, trungguyen commented on src/library/simplified/extension/marketingABTests.js
> +var marketingABTests = "3659,14698,14739,13542,12102";
We don't need to know the active marketing AB Tests in this extension.

2017-07-03 19:54 UTC, trungguyen commented on src/library/simplified/extension/marketingABTests.js
> +var marketingABTestsArray = marketingABTests.split(",");
Not needed.

2017-07-03 19:54 UTC, trungguyen commented on src/library/simplified/extension/marketingABTests.js
> +    for (var marketingABTest=0; marketingABTest<marketingABTestsArray.length; marketingABTest++) {
We just need a single for loop to flatten the "tests" list, where you grab all the tests and their corresponding buckets and combined them all into one long string. Basically all you need to do for this extension is iterate through "tests" list and take each test and its bucket to concat them into the string format "testId.bucketId|testId.bucketId|testId.bucketId|...", and assign the string to a new udo variable, in this case marketingABTests, that you create in this extension. That's pretty much it, just make sure you set this extension to run prior to load rules. Then this string will be used in a load rule. For example, if we want a load rule to fire a tag based on a given marketing test ID defined (or given by) marketing team, let's say 12345, we will then have a load rule to check and see if "12345.1" exists in the string, marketingABTests, created by this extension. If the "marketingABTests" contains "12345.1".  I have outlined the steps for this under "Tealium" section of the confluence page.

2017-07-04 20:41 UTC, trungnguyenexp commented on src/library/simplified/extension/marketingABTests.js
> +marketingABTests = marketingABTests.substring(0,marketingABTests.length - 1);
This is not necessary. one less instruction will help speed things up especially we don't want the page to be slow, but you can leave it as is if you want :).

2017-07-04 20:42 UTC, trungnguyenexp commented on src/library/simplified/extension/marketingABTests.js
> +var abTests = utag_data.context.tests;
Please make sure an automation test case in Tag Management is created for to check for marketingABTests existent and it is not empty/null.

2017-07-04 20:44 UTC, trungnguyenexp reviewed
please see comments

2017-07-05 06:07 UTC, merged