Enable logging to kafka and updating existing tag templates to also l…
ExpediaInc/expedia-omg-tags pull request #39
Opened 2017-01-27 21:27 UTC by ghardiya

…og pixel data on test collector-web

2017-01-27 23:41 UTC, tyang-expedia requested changes

2017-01-27 23:41 UTC, tyang-expedia commented on src/library/required/extension/omg-pixel-collector-web-preloader.js
> +                return base + '/' + messageType + '.json?stream=false&persist=true&batch=' + batched;
i'd rather have it more like being passed an object with the config.

so more
```
function getCollectorWebResource(messageType, config) {
  var base = (omg.isProd() ? COLLECTOR_WEB_PROD : COLLECTOR_WEB_TEST) + '/' + messageType + '.json?;
  var first = true;
  for (var key in config) {
    if (!first) {
      base += '&';
    }
    base += key + '=' + config[key];
  }
  return base;
```
and have config be an object like {batch: true, persist: true, stream: !omg.isProd()}

2017-01-27 23:52 UTC, ghardiya commented on src/library/required/extension/omg-pixel-collector-web-preloader.js
> +                return base + '/' + messageType + '.json?stream=false&persist=true&batch=' + batched;
@tyang-expedia will create config for persist and stream. We always want batch = true

2017-01-28 01:07 UTC, tyang-expedia commented
am i supposed to be reviewing the tags, too, or has that already been done?

2017-01-28 01:07 UTC, tyang-expedia approved these changes

2017-01-30 18:39 UTC, merged