fix undefined fields for cesc
ExpediaInc/expedia-omg-tags pull request #82
Opened 2017-03-16 04:22 UTC by trungnguyenexp

2017-03-16 15:27 UTC, wmoussa commented
what is the trello card that tirggered this work?

2017-03-16 15:33 UTC, wmoussa requested changes

2017-03-16 15:33 UTC, wmoussa commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +// Old logic that goes through cesc fields to find last touch and then set DTL.
if old logic, why is it still getting executed?

2017-03-16 15:33 UTC, wmoussa commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +// Use CID for last touch
don't use acronym, CID could be mean anything..

2017-03-16 15:33 UTC, wmoussa commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +if(b["cescLastTouchMarketingCode"].split(".").length >= 4){
how do you guarantee cescLastTouchMarketingCode is defined?

2017-03-16 15:33 UTC, wmoussa commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +    b["cescChannel"] = b["cescLastTouchMarketingCode"].split(".")[0];
you should just prepare the array once, instead of splitting each time

2017-03-18 18:58 UTC, trungnguyenexp commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +// Old logic that goes through cesc fields to find last touch and then set DTL.
This comment has always been there. This PR showed that I added it but I didn't. I guess things get shifted around when I copy the code to a text editor to modify and then copy it back to the extension.

2017-03-18 18:59 UTC, trungnguyenexp commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +// Use CID for last touch
Same as above. I didn't add it but will find out what it stands for and update it.

2017-03-18 19:00 UTC, trungnguyenexp commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +if(b["cescLastTouchMarketingCode"].split(".").length >= 4){
Same as above, I didn't add 58, only line 55-57.

2017-03-18 19:01 UTC, trungnguyenexp commented on src/library/simplified/extension/cesc-LT-channel-country-network-DTL.js
> +    b["cescChannel"] = b["cescLastTouchMarketingCode"].split(".")[0];
Same as above, I didn't add this, it has been like this for a while, but I can update.

2017-03-18 19:03 UTC, trungnguyenexp commented
This PR causes a lot of confusion. I will close this one and will close another one that is more readable.

2017-03-18 21:47 UTC, closed without merging

2017-03-18 22:11 UTC, trungnguyenexp commented
new PR here https://github.com/ExpediaInc/expedia-omg-tags/pull/86

2017-03-18 22:11 UTC, trungnguyenexp commented
new PR here: https://github.com/ExpediaInc/expedia-omg-tags/pull/86